services:
  - type: web
    name: stickdrift-web
    runtime: static
    buildCommand: echo "No build step"
    staticPublishPath: web
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
